import type { Metadata } from "next";
import "./globals.css";
import Siderbar from "./_components/siderbar";
import { Inter } from 'next/font/google'



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  display: 'auto',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <div className="flex gap-8 h-full">
          <Siderbar />
          {children}
        </div>
      </body>
    </html>
  );
}
